### ISSUE TITLE
Null-Pointer access with vararg function

### ISSUE THREAD

**Issue by Ingrater** [Ingrater/dmd#2]
Repro case (compile with: dmd -m64)

import std.stdio;

void printargs(int x, ...)
{
    writefln("%d arguments\n", _arguments.length);
    auto v = _arguments[0].toString();             // error, accessing null
}

void main()
{
    printargs(1, 10, 23, 40);
}

**Comment by skl131313** [comment]
I'll look into this.

**Comment by Ingrater** [comment]
I've already taken a brief look. Comparing the disassembly of the last released version of dmd and my modified version didn't give any difference. So the bug is connected to the static data or initializers and not connected to code generation. One possible place to look would be todt.d

**Comment by Ingrater** [comment]
While the PR fixes the issue when not using shared phobos the issue still exists with shared phobos.

**Comment by skl131313** [comment]
Hmm if you switch to it's own data symbol array. The array it fills it with need an extra indirection. If you have any suggestions.

```D
        scope dtbargs = new DtBuilder();
        Array!DataSymbolRef dataSymbolRefArgs; // <--- changed
        for (size_t i = 0; i < dim; i++)
        {
            Parameter arg = (*tu.arguments)[i];

            genTypeInfo(arg.type, null);
            dtxoffDsymbol(dtbargs, arg.type.vtinfo, 0, &dataSymbolRefArgs); // <--- changed
        }

        // expecting TypeInfo*[] but is essentially getting TypeInfo**[], as symbol is in DLL

```

**Comment by Ingrater** [comment]
Yeah, the array data needs to be placed into the same dt as the tuple info. I'm going to implement this tomorrow.

**Comment by Ingrater** [comment]
Fixed in https://github.com/Ingrater/dmd/commit/8ef670c943137a5968a1ce01776645ec9767a3e8
