### ISSUE TITLE
Add a way to identify if a DLL wasn't loaded.

### ISSUE THREAD

**Issue by skl131313** [Ingrater/dmd#4]
If a DLL can't be loaded (eg phobos64s.dll) then the program just crashes/closes without specifying which DLL couldn't be loaded. Not really a bug so much as a feature that isn't present.

**Comment by Ingrater** [comment]
phobos64s.dll is not loaded by any user code. Its linked in via a import library. This means it is the task of the operating system load to give an error message in case it fails to load. On my system, when phobos64s.dll is missing, I get a message box saying "phobos64s.dll could not be found". Unless I'm misunderstanding the issue there is not really anything you can do about this.

**Comment by skl131313** [comment]
That's odd, I don't get that error message. Is it a linker switch? I just tried quickly with a C++ visual studio project and it does give me an error about the DLL missing. For a program made with DMD though it just silently fails, so I'm not sure what's causing it.

**Comment by Ingrater** [comment]
No, this is a buildin feature of windows. Which version of windows are you using? Its possible that its a developer feature that needs to be enabled. I'm on Win7 an there its default on.

**Comment by skl131313** [comment]
I am on Win10, but it does it for my C++ program. If it's a windows feature I don't know why it works for one but not the other.

**Comment by Ingrater** [comment]
Good question. Are you sure that the dll is really missing or maybe its a different issue why the executable exits? Did you try attaching a debugger?

**Comment by skl131313** [comment]
Ah it only shows that if you don't execute from the command line.
