### ISSUE TITLE
Unresolved External Symbol for object._xopEquals

### ISSUE THREAD

**Issue by skl131313** [Ingrater/dmd#9]
Don't think it's a problem with druntime.
A small program that causes the link error. I'm also seeing similar link errors for _xopCmp as well.

Command used:
`dmd -m64 -useShared -defaultlib=phobos64s.lib main.d`

Error:
`LNK2001: unresolved external symbol _D6object10_xopEqualsFxPvxPvZb`

```D
import std.array;

void main()
{
	import std.algorithm.comparison : equal;
	struct Foo
	{
		int a;
		void opAssign(Foo foo)
		{
			assert(0);
		}
		auto opEquals(Foo foo)
		{
			return a == foo.a;
		}
	}
	auto a = array([Foo(1), Foo(2), Foo(3), Foo(4), Foo(5)][]);
	assert(equal(a, [Foo(1), Foo(2), Foo(3), Foo(4), Foo(5)]));
}
```

**Comment by Ingrater** [comment]
This was a easy fix, There was simply an export missing in druntime/src/object.d see https://github.com/Ingrater/druntime/commit/a392b15bc89a513c629cb5c60bd50001116fe3d2

**Comment by skl131313** [comment]
My bad could have swore I searched druntime for those functions.
